const COLORS = {
    temperature: [{
        min: -50,
        max: -25,
        color: "#784cff"
    }, {
        min: -25,
        max: -20,
        color: "#784cff"
    }, {
        min: -20,
        max: -15,
        color: "#0f5abe"
    }, {
        min: -15,
        max: -10,
        color: "#1380ff"
    }, {
        min: -10,
        max: -5,
        color: "#19cdff"
    }, {
        min: -5,
        max: -0,
        color: "#8fffff"
    }, {
        min: -0,
        max: 5,
        color: "#b0ffbc"
    }, {
        min: 5,
        max: 10,
        color: "#ffff73"
    }, {
        min: 10,
        max: 15,
        color: "#ffbe7d"
    }, {
        min: 15,
        max: 20,
        color: "#ff9b41"
    }, {
        min: 20,
        max: 25,
        color: "#ff5a41"
    }, {
        min: 25,
        max: 30,
        color: "#ff1e23"
    }, {
        min: 30,
        max: 50,
        color: "#fa3c96"
    }], 

    height: [{
        min: -100,
        max: -0.000001, 
        color: "#ffffff"
    },        
        {
        min: 0,
        max: 10,
        color: "#ffffb2"
    }, {
        min: 10.1,
        max: 25,
        color: "#b0ffbc"
    }, {
        min: 25.1,
        max: 50,
        color: "#8cffff"
    }, {
        min: 50.1,
        max: 100,
        color: "#19cdff"
    }, {
        min: 100.1,
        max: 200,
        color: "#1982ff"
    }, {
        min: 200.1,
        max: 300,
        color: "#0f5abe"
    }, {
        min: 300.1,
        max: 400,
        color: "#784bff"
    }, {
        min: 400.1,
        max: 10000,
        color: "#cd0feb"
    }]
}